### ISSUE TITLE
Unable to update logo on Open EDX LMS and CMS

### ISSUE THREAD

**Issue by dammmyt** [vlead/edx#14]
Hi,
I was trying to customize the open edx installation but the header logo and the organization logo in the footer is not updating on the lms and studio pages.

I updated logo.png in the /edx/var/edxapp/staticfiles/images/ folder.
and run the following commands to compile assets manually  
sudo -H -u edxapp bash
source /edx/app/edxapp/edxapp_env
cd /edx/app/edxapp/edx-platform
paver update_assets cms --settings=aws
paver update_assets lms --settings=aws

then i restarted the lms/cms services
sudo /edx/bin/supervisorctl restart all

Kindly find attached the screen shots

![studio](https://cloud.githubusercontent.com/assets/19290837/15155298/c5327f56-16d9-11e6-923c-3743e8aa1a26.png)
![lms page](https://cloud.githubusercontent.com/assets/19290837/15155304/c9163194-16d9-11e6-95fe-83c4675c11d0.png)

**Comment by ashay-maheshwari** [comment]
@dammmyt , our document is working fine with dogwood-0 version. We were unable to apply theming in dogwood-1. 
Still you can check the name of image which should be logo.png

**Comment by dammmyt** [comment]
We finally fixed the issue by changing the file permissions of the logo to allow the file read, write, and executable
