### ISSUE TITLE
Customize LMS homepage

### ISSUE THREAD

**Issue by dammmyt** [vlead/edx#16]
We will like to customize the LMS page to change the following:
1. Update information in default pages: tos, privac policy, about us, donor, contact, blog
2. Remove default links like donate if not needed on the page
3. Update the banner with details "Welcome to Open edX!. It works! This is the default homepage for this Open edX instance." 
and change it to a scrolling banner with different images
4. Include social media links (i.e. twitter, facebook, linkedIn) in the footer

![lmspage](https://cloud.githubusercontent.com/assets/19290837/15353931/31c52218-1ce3-11e6-9370-96e6ee53b9ba.png)

**Comment by ashay-maheshwari** [comment]
@dammmyt , please refer our documentation [here](https://github.com/vlead/port-labs-to-openedx/blob/develop/src/theming-customization/customization.org)
