### ISSUE TITLE
Install Open edX platform and configure it

### ISSUE THREAD

**Issue by travula** [vlead/edx#2]
Open edX platform provides a studio to create content for a course ( read lab , in the context of virtual labs).   This is CMS part of the platform.

The labs once created are also hosted on the same platform which provides LMS.  

Documentation on installing, configuring and running the platform is [here](http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/)

**Comment by sivashankerN** [comment]
Setup Open edX platform using the steps given in https://openedx.atlassian.net/wiki/display/OpenOPS/Native+Open+edX+Ubuntu+12.04+64+bit+Installation (Used manual steps/installation)

For more information about how we have setup Open edX platform please go through the links https://github.com/vlead/port-labs-to-openedx/blob/develop/src/platform-installation/index.org and  https://github.com/vlead/port-labs-to-openedx/blob/develop/src/openedx-installation.org

**Comment by sivashankerN** [comment]
TODO tasks:
1.Remove default users from Open edX platform
2. Add/Create required users to login into LMS/CMS

**Comment by sivashankerN** [comment]
Above two tasks are done and documented in the following locations
1. Process to remove default users from Open edX platform is documented at https://github.com/vlead/port-labs-to-openedx/blob/develop/src/platform-installation/index.org#remove-default-users-from-open-edx-platform
2. Process to Add/Create required users to log in to LMS/CMS  https://github.com/vlead/port-labs-to-openedx/blob/develop/src/platform-installation/index.org#addcreate-required-users-to-log-in-to-lmscms

**Comment by sivashankerN** [comment]
Documentation is reviewed by Thirumal and incorporated the changes.
Complete documentation is at https://github.com/vlead/port-labs-to-openedx/tree/develop/src/platform-install-configure

**Comment by ashay-maheshwari** [comment]
Following things are working in LMS -
- Courseware
- Course Info , current location
- Discussion
- Wiki
- Progress
- Instructor
