### ISSUE TITLE
Requirement 4 : Port 30 labs to Open edX platform

### ISSUE THREAD

**Issue by ashay-maheshwari** [vlead/edx#29]
Porting a lab initially to Open edX is time consuming process. But an already ported lab can be exported and imported back easily. Intern will help us in porting 20-25 labs to Open edX LMS.

**Comment by priya100raman** [comment]
Course on porting to be developed.
Workshop on porting to be conducted. 
30 Labs to be ported by Oct 15th ( 15 will be ported by the VLEAD/IIITH team. 15 will be ported as part of the workshop. )

**Comment by priya100raman** [comment]
Feedback and spills from Release 2
- Send out invites along with the list of labs chosen for workshop. 
- Start preparation of a course on porting labs on to OpenEdX Platform.

**Comment by ashay-maheshwari** [comment]
All Labs with integration level 5 or 6 (75 labs) are Ported to VLABS Open edX.
