### ISSUE TITLE
Port 10 labs to Open edX platform

### ISSUE THREAD

**Issue by travula** [vlead/edx#3]
10 virtual labs are to be ported to Open edX platform. 

Lab list is accessed [here](https://github.com/vlead/port-labs-to-openedx/blob/develop/src/index.org#labs-chosen)

**Comment by dinnu93** [comment]
9 labs ported, Lab.No.6 is left in the above list.

**Comment by dinnu93** [comment]
Lab No.6 Ported to open edx. This means all 10 labs are ported to open edx

**Comment by travula** [comment]
10 labs are ported

**Comment by travula** [comment]
The process of porting is documented. 

https://github.com/vlead/port-labs-to-openedx/blob/develop/src/porting-labs/index.org

**Comment by sivashankerN** [comment]
Sanchita and Sripathi ported 10 labs to edx-courses.vlabs.ac.in.
